# Generated by Django 5.1.1 on 2024-10-07 14:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='User', max_length=100)),
                ('email', models.EmailField(default='test@test.com', max_length=270, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('available_balance', models.IntegerField(default=0)),
                ('savings_balance', models.IntegerField(default=0)),
                ('total_income', models.IntegerField(default=0)),
                ('total_expense', models.IntegerField(default=0)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expensecat', to='fin_tracker.expensecategory')),
                ('income_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incometype', to='fin_tracker.incometype')),
                ('savings_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savingstype', to='fin_tracker.savingstype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fin_tracker.user')),
            ],
        ),
    ]
