# Generated by Django 5.1.1 on 2024-10-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfact',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
