# Generated by Django 5.1.1 on 2024-10-07 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_tracker', '0002_transactionfact_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfact',
            name='expense_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expensecat', to='fin_tracker.expensecategory'),
        ),
        migrations.AlterField(
            model_name='transactionfact',
            name='income_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incometype', to='fin_tracker.incometype'),
        ),
        migrations.AlterField(
            model_name='transactionfact',
            name='savings_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savingstype', to='fin_tracker.savingstype'),
        ),
    ]
